#!/bin/bash

TMPFILE=/tmp/yorkeme.out

if [ ! -r $TMPFILE ]; then
    echo "Hmmm...no file....that's cool...."
	# Get the file fresh from manta....
##	mget  -q /ryanpuckett/stor/pyoogle.txt 
    cat $HOME/data/pyoogle.txt | sort  -u | egrep -v '^ '  | egrep -v '^ ' | egrep -v "^vm" | egrep -v "^zones/" | grep -v "^zfs" | egrep -v "^\|" | egrep -v "^{" | egrep -v "^<" | egrep -v "^}" | egrep -v "^─" | grep -v "^Password"  | egrep -v "^~" | egrep -v "^zlogin" | egrep -v "[^ -~]" | awk 'length($0)<140' | awk 'length($0)>10' | egrep -v "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}" | egrep "^[a-zA-Z]" > $TMPFILE
    echo "Done...and here we go!"
	echo " "
fi


# get line count for $TMPFILE (simulate 'wc -l')
lc=0
while read -r line; do
 ((lc++))
done < $TMPFILE

# get a random number between 1 and $lc
rnd=$RANDOM
let "rnd %= $lc"
((rnd++))

# traverse file and find line number $rnd
i=0
while read -r line; do
 ((i++))
 [ $i -eq $rnd ] && break
done < $TMPFILE

# output random line
printf '%s\n' "$line"

