#################################################
# DO Community Playbook
#################################################
---
- hosts: all
  remote_user: root
  gather_facts: false

  tasks:
    - name: Install Python
      raw: apt -y update && apt install -y python
    
    - name: Install Python3
      raw: apt -y update && apt install -y python3
  
    - name: Python Setuptools
      raw: apt install -y  python-setuptools
  
    - name: Python Pip
      raw: apt install -y  python3-pip
  
    - name: Aptitude
      raw: apt install -y  aptitude
  
    - name: Guest Agent
      raw: apt install -y  qemu-guest-agent

    - name: Enable guest agent
      service:
         name: qemu-guest-agent
         enabled: yes
         state: started

    - name: Install new packages
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'lsb-release', 'magic-wormhole', 'qemu-guest-agent' ]

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Make sure we have a 'kube' group
      group:
        name: kube
        state: present

    - name: Add the user 'kube' with a specific uid and a primary group of 'kube'
      user:
        name: kube
        comment: Openkube User
        group: kube

    - name: sudo without password for kube group
      copy:
        content: '%kube ALL=(ALL:ALL) NOPASSWD:ALL'
        dest: /etc/sudoers.d/kube_nopasswd
        mode: 0440 

    - name: Install MicroK8s Snap
      snap:
        name: microk8s
        classic: yes
        state: present

