container_count = 2
cores           = 2
disk_size       = "16G"
memory          = 2048
name_prefix     = "container"
network_bridge  = "vmbr0"
network_ipv4    = "dhcp"
network_model   = "virtio"
node            = ["prox04", "prox05", "prox06"]
proxmox_api_url      = "https://192.168.212.101:8006/api2/json"
proxmox_password     = "DrummerBoy1997"
proxmox_tls_insecure = "true"
proxmox_username         = "root@pam"
storage         = "ceph01"
template        = "iris:vztmpl/ubuntu-23.04-standard_23.04-1_amd64.tar.zst"
user_password   = "password"
ssh_keys = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDh6ROxdnUrSAmjyqzlpvcSFlXcSwD7VMp7PvCTzAtDePSluBiQq3njWW88Pcxgmhsqhsm/ZjRKTdFO5RWRt2YM3BsZQqIMlsulIKK426RavgtnMYpJuUhTkyVm1QQAaoOH4NvkBOk35VOWylzxSZFa2v+LExjOQzQM5CfXB2GX7KerNNvEMNuTnFQ5upuV8YOEeeeomfLmt/I8VMxFJiSQWlELkS2NBVbhWKHcRaE2T2X2eASaruqlDhSMgeE0K/8bRuLquvv5j0F3rQ6slbVi0zjdIMRUlwD4gsZOQaSiFrQceItR+slp3/2FT/o6uxW/lJu3sW5RkHNHMxubSFpl jschmidt@jack.virington.com"
